format = """
[░▒▓](#a3aed2)\
$os\
[](fg:#a3aed2 bg:#769ff0)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$python\
[](fg:#212736 bg:#1d2230)\
$status\
[ ](fg:#1d2230)\
\n$character"""

[status]
disabled = false
format = '[ $symbol$status ]($style)'
map_symbol = true
style = "bold red bg:#1d2230"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[os]
disabled = false
format = '[ $symbol ]($style)'
style = "fg:#090c0c bg:#a3aed2"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Macos = "󰀵"
Linux = "󰌽"
Alpine = ""
Debian = "󰣚"

[git_branch]
symbol = ""
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol $branch ]($style)'

[nodejs]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "🐍"
style = "fg:#769ff0 bg:#212736"
format = '[ $symbol ($version) ]($style)'

