[[plugins]]
repo = 'junegunn/fzf.vim'
on_cmd = [
  'Files',
  'ProjectFiles',
  'Buffers',
  'BLines',
  'History',
  'Tags',
  'BTags',
  'GFiles',
  'Ag',
  'Rg',
]
hook_add = '''
set rtp+=$XDG_CACHE_HOME/fzf
'''
hook_source = 'runtime! plugins/fzf.vim'

[[plugins]]
repo = 'Shougo/ddu.vim'
on_source = 'denops.vim'
hook_add = '''
nmap <silent> ,s <Cmd>call ddu#start({
\   'name': 'filer',
\   'uiParams': {
\     'filer': {
\       'search': expand('%:p')
\     }
\   },
\ })<CR>
nmap <silent> ,n <Cmd>call ddu#start({
\   'name': 'file',
\   'uiParams': {
\     'filer': {
\       'search': expand('%:p')
\     }
\   },
\   'sourceParams': {
\     'new': v:true,
\   },
\ })<CR>
'''
hook_source = '''
autocmd FileType ddu-filer call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer><silent><expr> <CR>
    \ ddu#ui#filer#is_directory() ?
    \ "<Cmd>call ddu#ui#filer#do_action('expandItem', {'mode': 'toggle'})<CR>" :
    \ "<Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'open'})<CR>"

  nnoremap <buffer><silent><expr> O
    \ ddu#ui#filer#is_directory() ?
    \ "<Cmd>call ddu#ui#filer#do_action('expandItem', {'mode': 'toggle', 'maxLevel': 10})<CR>" :
    \ ""
  nnoremap <buffer><silent> N
        \ <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'newFile'})<CR>
  nnoremap <buffer><silent> dd
        \ <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'delete'})<CR>

  nnoremap <buffer><silent> <Space>
        \ <Cmd>call ddu#ui#filer#do_action('toggleSelectItem')<CR>
  nnoremap <buffer> o
        \ <Cmd>call ddu#ui#filer#do_action('expandItem',
        \ {'mode': 'toggle'})<CR>
  nnoremap <buffer><silent> q
        \ <Cmd>call ddu#ui#filer#do_action('quit')<CR>
endfunction

call ddu#custom#patch_global({
    \   'ui': 'filer',
    \   'sources': [{ 'name': 'file' }],
    \   'sourceOptions': {
    \     '_': {
    \       'columns': ['filename'],
    \     },
    \   },
    \   'actionOptions': {
    \     'narrow': {
    \       'quit': v:false,
    \     },
    \   },
    \   'uiParams': {
    \     'filer': {
    \       'winWidth': 40,
    \       'split': 'vertical',
    \       'splitDirection': 'topleft',
    \     }
    \   },
    \   'kindOptions': {
    \     'file': {
    \       'defaultAction': 'open',
    \     },
    \   }
    \ })
'''

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-column-filename'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'chr4/nginx.vim'
on_ft = ['nginx']


[[plugins]]
repo = 'prettier/vim-prettier'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx','typescriptreact']
hook_source = '''
let g:prettier#autoformat = 1
let g:prettier#autoformat_require_pragma = 0
'''

