[[plugins]]
repo = 'junegunn/fzf.vim'
on_cmd = [
  'Files',
  'ProjectFiles',
  'Buffers',
  'BLines',
  'History',
  'Tags',
  'BTags',
  'GFiles',
  'Ag',
  'Rg',
]
hook_add = '''
set rtp+=$XDG_CACHE_HOME/fzf
'''
hook_source = 'runtime! plugins/fzf.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
on_cmd = ['Fern']
hook_add = '''
nmap <silent> ,s <Cmd>Fern . -drawer -reveal=%<CR>
'''
hook_source='''
let g:fern#default_hidden=1
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
on_source = ['fern.vim']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'chr4/nginx.vim'
on_ft = ['nginx']

[[plugins]]
repo = 'prettier/vim-prettier'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx','typescriptreact']
hook_source = '''
let g:prettier#autoformat = 1
let g:prettier#autoformat_require_pragma = 0
'''

