
[[plugins]]
repo = 'junegunn/fzf.vim'
on_cmd = [
  'Files',
  'ProjectFiles',
  'Buffers',
  'BLines',
  'History',
  'Tags',
  'BTags',
  'GFiles',
  'Ag',
  'Rg',
]
hook_add = '''
set rtp+=$XDG_CACHE_HOME/fzf
'''
hook_source = 'runtime! plugins/fzf.vim'

[[plugins]]
repo = 'nvim-tree/nvim-tree.lua'
on_cmd = ['NvimTreeToggle']
hook_add = '''
nnoremap <silent> <leader>s :<C-u>NvimTreeToggle<CR>
'''
lua_source='''

-- disable netrw at the very start of your init.lua (strongly advised)
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

-- set termguicolors to enable highlight groups
vim.opt.termguicolors = true

require'nvim-tree'.setup({
  update_focused_file = {
    enable = true,
  },
  actions = {
    open_file = {
      quit_on_open = true,
    },
  },
})
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
on_source = ['fern.vim']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'chr4/nginx.vim'
on_ft = ['nginx']

[[plugins]]
repo = 'sbdchd/neoformat'
on_cmd = ['Neoformat']
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx', 'typescriptreact', 'vue']
hook_source = '''
let g:neoformat_try_node_exe = 1
let g:neoformat_enabled_javascript = ['prettier', 'jsbeautify']
command! -range=% Fmt :mkview | :<line1>,<line2>Neoformat | :loadview
augroup fmt
  autocmd!
  autocmd BufWritePre * Fmt
augroup END
'''

[[plugins]]
repo = 'cohama/lexima.vim' # かっこの自動補完
on_event = 'InsertEnter'
hook_source = 'runtime! plugins/lexima.vim'


[[plugins]]
repo = 'kana/vim-textobj-user'
on_event = 'VimEnter'

[[plugins]]
repo = 'vim-scripts/surround.vim'
on_event = 'VimEnter'
hook_source = '''
nmap s ys
'''

[[plugins]]
repo = 'tpope/vim-repeat'
on_event = 'VimEnter'
hook_source = '''
" function s:execute_repeatable_macro(name) abort
function! Execute_repeatable_macro(name)
  const name = '@' .. a:name

  execute 'normal!' name
  silent! call repeat#set("\<Plug>macro_" .. a:name)
endfunction

for x in ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
  execute 'nnoremap' '<silent>' ("<Plug>macro_" .. x) (":\<C-u>call Execute_repeatable_macro('" .. x .. "')\<CR>")
  execute 'nmap' ('@' .. x) ("<Plug>macro_" .. x)
endfor
'''

[[plugins]]
repo = 'justinmk/vim-sneak'
on_event = 'VimEnter'

[[plugins]]
repo = 'tomtom/tcomment_vim'
on_event = 'VimEnter'
hook_source = '''
au MyAutoCmd VimEnter * nnoremap <silent> <Plug>RepeatTComment :TComment \| silent! call repeat#set("\<Plug>RepeatTComment")<CR>
au MyAutoCmd VimEnter * nmap <c-_><c-_> <Plug>RepeatTComment
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
on_event = 'BufRead'
hook_source = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd guibg=none ctermbg=none
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#2e3248 ctermbg=0
'''

