[[plugins]]
repo = 'anuvyklack/pretty-fold.nvim'
lua_add = '''
require('pretty-fold').setup()
'''

[[plugins]]
repo = 'anuvyklack/keymap-amend.nvim'

[[plugins]]
repo = 'anuvyklack/fold-preview.nvim'
depends = ['keymap-amend.nvim']
lua_add = '''
require('fold-preview').setup()
'''

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = 'runtime! plugins/nvim-lspconfig.vim'

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add='''
let g:tokyonight_style = 'night'
let g:tokyonight_transparent_background = 1
colorscheme tokyonight
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_source = '''
let g:lightline = {'colorscheme': 'tokyonight'}
let g:lightline.separator = {'left': "\ue0bc", 'right': "\ue0ba"}
let g:lightline.subseparator = {'left': "\ue0bd", 'right': "\ue0bb"}
'''
hook_add = '''
let g:lightline = {
  \'colorscheme': 'tokyonight',
  \ 'active': {
  \   'right': [['lineinfo'], ['percent'],[ 'fileformat', 'fileencoding', 'filetype', 'charvaluehex']]
  \ }
\}

let g:lightline.separator = {'left': "\ue0bc", 'right': "\ue0ba"}
let g:lightline.subseparator = {'left': "\ue0bd", 'right': "\ue0bb"}
'''

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'
