source "$ZDOTDIR/utils.zsh"
command_exists() { type "$1" > /dev/null 2>&1; }

# emacsのtrampがタイムアウトするのに対応
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ '

bindkey -e

# 自作関数の読み込み
autoload -Uz tinify estart

autoload -U colors; colors

git-prompt() {
  local branchname
  branchname=`git symbolic-ref --short HEAD 2> /dev/null`
  if [ -z $branchname ]; then
    return
  fi
  echo "%{${fg[magenta]}%}${branchname}%{${reset_color}%}"
}
prompt-set(){
    PROMPT="%F{074}[%n@%m]%f# "
    RPROMPT='`git-prompt`%F{048}[%~]%f'
}
prompt-reset() {
    PROMPT="# "
    RPROMPT=''
}
prompt-set
setopt prompt_subst #表示毎にPROMPTで設定されている文字列を評価する

setopt no_beep # ビープ音を消す
setopt globdots # 明確なドットの指定なしで.から始まるファイルをマッチ

setopt auto_cd
function chpwd() {
    if is_mac; then
        ls -G
    else
        ls --color=auto
    fi
}

# コマンド履歴関連
setopt hist_ignore_dups
setopt hist_ignore_space
setopt share_history
SAVEHIST=100
HISTFILE=$HOME/.zsh_history

# 補完
autoload -U compinit
if compinit; then
  zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
  zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
  zstyle ':completion:*:default' menu select=1
  zstyle ':completion:*' menu select
  zstyle ':completion:*' use-cache true
  zstyle ':completion:*' cache-path $XDG_CACHE_HOME/zsh/cache
  setopt auto_list
  setopt IGNOREEOF
  setopt auto_menu
  _ssh() {
    compadd `grep '^Host ' ~/.ssh/config | awk '$0=$2' | sort`
  }
  compdef _ssh ssh
fi
# setopt menu_complete

if command_exists fasd; then
    eval "$(fasd --init auto)"
fi

source "$ZDOTDIR/zinit.zsh"

# ローカルファイルの読み込み
file_exists "$XDG_CACHE_HOME/fzf/shell/completion.zsh" && source "$XDG_CACHE_HOME/fzf/shell/completion.zsh"
file_exists "$XDG_CACHE_HOME/fzf/shell/key-bindings.zsh" && source "$XDG_CACHE_HOME/fzf/shell/key-bindings.zsh"
source "$ZDOTDIR/alias.zsh"
source "$ZDOTDIR/keybind.zsh"
file_exists "$ZDOTDIR/.zshrc.local" && source "$ZDOTDIR/.zshrc.local"
source "$ZDOTDIR/launch_tmux.zsh"

