source "$ZDOTDIR/utils.zsh"

if [[ "$MULTIPLEXERS" == "tmux" ]] &&
  command_exists tmux &&
  [ $(whoami) != 'root' ] &&
  [[ "$TMUX_AUTO_LAUNCH" == "true" ]] &&
  is_empty_string "$TMUX" &&
  is_empty_string "$STY" &&
  is_empty_string $IS_VSCODE &&
  is_empty_string $GITHUB_ACTIONS; then
  source "$ZDOTDIR/launch_tmux.zsh"
  exit
fi

if [[ "$MULTIPLEXERS" == "zellij" ]] && command_exists zellij && [[ -z "$ZELLIJ" ]]; then
  if [[ "$ZELLIJ_AUTO_ATTACH" == "true" ]]; then
    zellij attach -c main
  else
    zellij
  fi

  if [[ "$ZELLIJ_AUTO_EXIT" == "true" ]]; then
    exit
  fi
fi

# emacsのtrampがタイムアウトするのに対応
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ '

bindkey -e

autoload -U colors
colors

source "$ZDOTDIR/set_prompt.zsh"

setopt no_beep  # ビープ音を消す
setopt globdots # 明確なドットの指定なしで.から始まるファイルをマッチ

setopt auto_cd
function chpwd() {
  if is_mac; then
    ls -G
  else
    ls --color=auto
  fi
}

# コマンド履歴関連
setopt hist_ignore_dups
setopt hist_ignore_space
setopt share_history
SAVEHIST=100
HISTFILE=$HOME/.zsh_history

# 補完
source "$ZDOTDIR/init_completion.zsh"

if command_exists fasd; then
  eval "$(fasd --init auto)"
fi

source "$ZDOTDIR/zinit.zsh"

# ローカルファイルの読み込み
file_exists "$XDG_CACHE_HOME/fzf/shell/completion.zsh" && source "$XDG_CACHE_HOME/fzf/shell/completion.zsh"
file_exists "$XDG_CACHE_HOME/fzf/shell/key-bindings.zsh" && source "$XDG_CACHE_HOME/fzf/shell/key-bindings.zsh"
source "$ZDOTDIR/alias.zsh"
source "$ZDOTDIR/keybind.zsh"
file_exists "$ZDOTDIR/.zshrc.local" && source "$ZDOTDIR/.zshrc.local"

if command_exists starship; then
  eval "$(starship init zsh)"
fi
